name: Gestao de vagas application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: actions/checkout@v3
      - name: Setup Java
        with:
          distribution: temurin
          java-version: 17